# Generated by Django 2.2.12 on 2020-05-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('match_type', models.CharField(max_length=50)),
                ('match_mode', models.CharField(max_length=50)),
                ('match_time', models.TimeField()),
                ('match_status', models.CharField(choices=[('upcoming', 'UpComing'), ('open', 'Open'), ('running', 'Running'), ('over', 'Over')], max_length=10)),
            ],
        ),
    ]
