# Generated by Django 2.2.12 on 2020-05-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match_1_Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerid', models.IntegerField()),
                ('pnayername', models.CharField(max_length=20)),
                ('paid_through', models.CharField(choices=[('account', 'Account'), ('bkash', 'Bkash')], max_length=10)),
                ('txnid', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match_2_Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerid', models.IntegerField()),
                ('pnayername', models.CharField(max_length=20)),
                ('paid_through', models.CharField(choices=[('account', 'Account'), ('bkash', 'Bkash')], max_length=10)),
                ('txnid', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match_3_Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerid', models.IntegerField()),
                ('pnayername', models.CharField(max_length=20)),
                ('paid_through', models.CharField(choices=[('account', 'Account'), ('bkash', 'Bkash')], max_length=10)),
                ('txnid', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match_4_Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerid', models.IntegerField()),
                ('pnayername', models.CharField(max_length=20)),
                ('paid_through', models.CharField(choices=[('account', 'Account'), ('bkash', 'Bkash')], max_length=10)),
                ('txnid', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match_5_Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerid', models.IntegerField()),
                ('pnayername', models.CharField(max_length=20)),
                ('paid_through', models.CharField(choices=[('account', 'Account'), ('bkash', 'Bkash')], max_length=10)),
                ('txnid', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match_6_Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerid', models.IntegerField()),
                ('pnayername', models.CharField(max_length=20)),
                ('paid_through', models.CharField(choices=[('account', 'Account'), ('bkash', 'Bkash')], max_length=10)),
                ('txnid', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
