# Generated by Django 2.2.12 on 2020-05-18 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_1_player_match_2_player_match_3_player_match_4_player_match_5_player_match_6_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match_1_player',
            old_name='pnayername',
            new_name='playername',
        ),
        migrations.RenameField(
            model_name='match_2_player',
            old_name='pnayername',
            new_name='playername',
        ),
        migrations.RenameField(
            model_name='match_3_player',
            old_name='pnayername',
            new_name='playername',
        ),
        migrations.RenameField(
            model_name='match_4_player',
            old_name='pnayername',
            new_name='playername',
        ),
        migrations.RenameField(
            model_name='match_5_player',
            old_name='pnayername',
            new_name='playername',
        ),
        migrations.RenameField(
            model_name='match_6_player',
            old_name='pnayername',
            new_name='playername',
        ),
    ]
