# Generated by Django 2.2.12 on 2020-05-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_auto_20200518_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_status',
            field=models.CharField(choices=[('upcoming', 'UpComing'), ('open', 'Open'), ('full', 'Full'), ('running', 'Running'), ('over', 'Over')], max_length=10),
        ),
    ]
