# Generated by Django 2.2.12 on 2020-05-14 18:46

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='temp_player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pubg_name', models.CharField(max_length=20)),
                ('pubg_id', models.IntegerField()),
                ('mobile', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('otp', models.CharField(max_length=6, unique=True)),
                ('otp2', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('otp3', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('session', models.CharField(max_length=10, unique=True)),
                ('exp_time', models.DateTimeField(default=datetime.datetime(2020, 5, 14, 18, 51, 15, 286518))),
            ],
        ),
        migrations.CreateModel(
            name='players',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('pubg_name', models.CharField(max_length=20, unique=True)),
                ('pubg_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('mobile', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+8801xxxxxxxxx' or '01xxxxxxxxx'. ", regex='^(?:\\+88|01)?(?:\\d{11})$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
