# Generated by Django 2.2.12 on 2020-05-14 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_player',
            name='exp_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 18, 51, 31, 946921)),
        ),
    ]
