# Generated by Django 2.2.12 on 2020-05-18 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0002_auto_20200514_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_player',
            name='exp_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 16, 55, 44, 854912)),
        ),
    ]
