# Generated by Django 2.2.12 on 2020-05-18 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0004_auto_20200518_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_player',
            name='exp_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 17, 59, 52, 556367)),
        ),
    ]
